### ISSUE TITLE
Rainfall overflowing

### ISSUE THREAD

**Issue by kppr0** [blackadderkate/weather-widget-2#119]
- Rainfall overflows at the end of time axis
- Rainfall is not respecting system colour (WW1 vs WW2); maybe blue colour of rain is a feature :-)

![screen](https://user-images.githubusercontent.com/116163807/197244518-5a312495-9cb7-4a55-81e3-ea6dbf5405f6.png)

P.S. Please pull translation request https://github.com/blackadderkate/weather-widget-2/pull/118

**Comment by blackadderkate** [comment]
I will have a look at the overflow!

Blue is a feature - I changed the rain colour deliberately as I had trouble seeing it on the theme I was using at the time. Also, if you use accent colours you can end up with Pink Rain (I suppose a Prince fan might like Purple Rain though!).

Since Blue seems to be the colour most often associated with Rain, I chose Light Blue (on Dark themes) and Dark Blue (on Light themes)...

I suppose I could make the Meteogram colours customisable - I'll add that as a separate issue as a feature request...

**Comment by kppr0** [comment]
Thanks for explanation, blue colour of rain is fine :-)

Maybe it is related with overflow, I noticed that for the same location, Yr forecast is 60 hours, OpenWeatherMap 55 hours:
![screen](https://user-images.githubusercontent.com/116163807/197387547-f6faa64a-8a2a-446f-ba95-c7c8b63718d5.png)

Please merge https://github.com/blackadderkate/weather-widget-2/pull/118 :-)

**Comment by blackadderkate** [comment]
I have just uploaded a fix for this issue.

Please try downloading and installing [this new beta version](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.3.4.2/weather-widget-2.3.4.2.plasmoid).

**Comment by kppr0** [comment]
Still not correct, version 2.3.4.2:

![screen](https://user-images.githubusercontent.com/116163807/199543179-798e85ad-b392-43e2-8526-39bbac5685a3.png)

**Comment by kppr0** [comment]
Thank you, overflow is fixed.
