### ISSUE TITLE
permit lower refresh intervals

### ISSUE THREAD

**Issue by alsoGAMER** [blackadderkate/weather-widget-2#133]
in the current state, the lowest refresh interval possibile is limited to 20 minutes, which in some cases isn't low enough to provide a precise forecast.
i know that there's a manual refresh button in the widget main ui, but having the possibility to set a lower interval is just better.

**Comment by blackadderkate** [comment]
The free MetNo API this widget uses has a limit on the number of requests that can be made per day.
If I reduce the refresh interval, the number of requests the widget makes will increase, and the chances of being blacklisted also increase, in which case it would stop working for everybody.

 I am going to mark this as WONTFIX, because there is already a workaround if you really need to refresh more frequently...

**Comment by alsoGAMER** [comment]
> because there is already a workaround if you really need to refresh more frequently...

Can you link it?

> If I reduce the refresh interval, the number of requests the widget makes will increase

This isn't what i was asking for, i asked if you can remove the 20 min hard limit, for people like me who wants a more precise forecast.
