### ISSUE TITLE
MetNo sources no longer loading

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#149]
MetNo sources are no longer working for me on Kubuntu 22.04LTS
Framework 5.98

**Comment by blackadderkate** [comment]
It seems something is being proxied - the Timezone API now returns HTTP status code 203 Non-Authoritative Information. Possibly using Varnish now.

Change code to accept http status 203 as a successful query.

**Comment by martin-ms** [comment]
Discovered the same problem since yesterday morning, that the connection to MetNo was broken.
I can confirm that it works now again for me after update to ver 2.3.5beta

**Comment by solbu** [comment]
Confirmed here also.
After applying the patch to the latest packaged release v2.3.4 it works again in Mageia too.

May I suggest a proper release in the comming days, so the distros will start picking up the new version.

Good job Kate. :-)

**Comment by pstrejajo** [comment]
I stumbled upon the same issue last Thursday. I searched a bit and it turns out that Sunrise 2.0 API (https://api.met.no/weatherapi/sunrise/2.0/documentation) is deprecated now (https://lists.met.no/pipermail/api-users/2023-May.txt), hence the status 203 according to ToS (https://api.met.no/doc/TermsOfService). 

Fortunately migration to Sunrise 3.0 (https://api.met.no/weatherapi/sunrise/3.0/documentation) seems quiet straightforward.
