### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by solbu** [blackadderkate/weather-widget-2#19]
Hi.
I am translating the program into norwegian, and came across a string that looks like it should under no circumstances be translated.

The string «weather-clouds» seems to only appear in the desktop file «package/metadata.desktop».
In line 4 on the desktop file  you have «Icon=weather-clouds»

That string is the filename for the icon used and should not be translated, unless you plan on shipping a separate localized icon for each possible translation language. ;-)

**Comment by blackadderkate** [comment]
That's odd!
I followed the instructions on the KDE i18n developer page precisely - to be honest I think it's a bug in their merge.sh script...
I've had a quick look at the script, but I'm not familiar with xgettext so it might not be a quick fix - fortunately no-one has attempted to translate that particular entry yet, so I don't have to panic!

**Comment by blackadderkate** [comment]
I've done some research, and [it's a bug](https://savannah.gnu.org/support/?108887) in the version of gettext installed on my machine. According to the bug report, it was fixed in version 0.20.2 - unfortunately my Kubuntu 20.04 LTS release only comes with version 0.19.8.1.

So I can either [use the workaround](https://savannah.gnu.org/support/?108887#comment14), or download the gettext source code and compile it myself. And to be honest, compiling a newer version seems like an awful lot of work!

**Comment by blackadderkate** [comment]
Uploaded the following commits.
fa5b3a8
28e184e
Prevent the metadata.desktop Icon text from being extracted by the merge script: Check the version of xgettext, and add some extra parameters to xgettext if necessary.
Remove the Icon entries from the Template and existing translations.

**Comment by Zren** [comment]
My bad, [I added the ability](https://github.com/Zren/plasma-applet-lib/commit/1d09df474ccdfbbef5dac9f532f4a2ed0bdff547) to parse the keys in the `metadata.desktop` file in July 2020. I developed in Manjaro which probably had the latest xgettext version at the time. https://ftp.gnu.org/pub/gnu/gettext/ mentions `gettext-0.20.2.tar.xz` was created 2020-04-14 so I had no idea this bug was possible.

I'll look into merging that fix into the script in the widget documentation. Is there a reason you only call `-k -kName -kGenericName -kComment -kKeywords` when it's not `0.20.2` or `0.21.x`.

**Comment by blackadderkate** [comment]
> My bad, [I added the ability](https://github.com/Zren/plasma-applet-lib/commit/1d09df474ccdfbbef5dac9f532f4a2ed0bdff547) to parse the keys in the `metadata.desktop` file in July 2020. I developed in Manjaro which probably had the latest xgettext version at the time. https://ftp.gnu.org/pub/gnu/gettext/ mentions `gettext-0.20.2.tar.xz` was created 2020-04-14 so I had no idea this bug was possible.
> 
> I'll look into merging that fix into the script in the widget documentation. **Is there a reason you only call `-k -kName -kGenericName -kComment -kKeywords` when it's not `0.20.2` or `0.21.x`.**

Yes.
Basically those parameters were suggested as a [workaround](https://savannah.gnu.org/support/?108887#comment14) on the GNU bug-tracking website page discussing the issue.
Since it was fixed in version 0.20.2, I only need to use those parameters on versions of xgettext earlier than that...
