### ISSUE TITLE
Make placeSearch the Master Branch

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#22]
When I decided to create a search engine for Met.No places, I created a "placeSearch" branch for my development work.
This went much more smoothly, and ended up taking much less time (and disk space), than I expected - so I now want to make this branch the "Master" branch.

I contributed a couple of patches to Mozilla Application Suite / Seamonkey many years ago, but they used CVS, and I have no idea how to do this with Git, and I have no idea how this will affect the people who forked my repository.

**Comment by solbu** [comment]
Git is a lot easier to work with branches and patches than CVS ever was.
And syncing from your original into our forks is easy, so don't worry about that. :-)

**Comment by solbu** [comment]
Just checked this issue again after my problems testing the 1.2.7a pre-release. (issue #29)

If you want to move the changes in this branch into the master branch, you need to merge it into the master branch.
I did a merge test, and I had to use the merge option «--strategy-option=theirs» for a successfull merge.

1: git checkout master
2: git merge --strategy-option=theirs placeSearch

**Comment by blackadderkate** [comment]
OK, thanks for the tips. As I said I'm a noob on Git, and I think I configured the "development" and "stable" branches the wrong way around...

I have a couple more checkins to do (after more testing and tidying up of code) and then I will do the merge...
These checkins will add Daylight Savings awareness and Timezone support (required to properly fix issue #1), and also the ability to edit places you have already configured...

This new release will probably end up being version 2.2.0.

**Comment by solbu** [comment]
> As I said I'm a noob on Git, and I think I configured the "development" and "stable" branches the wrong way around...

What I've noticed is that those who have a devel branch and a stable branch is that master is the stable branch.

The normal workflow in a git based development is to do feature testing in a separate branch, like you do in the placeSearch branch in case the feature turns out to be undesired for whatever reason (so it doesn't make problems for the master branch), and when it is ready for use they merge it into the master branch.

When distros check for new releases on a github project, they only check the releases or the tags page, depending on how the various github projects do releases. Rarely do they bother with which branch a release is made from.

**Comment by blackadderkate** [comment]
FYI, I have just created a 2.0.6 archive branch (containing the old Master branch) and merged the placeSearch branch into Master.
