### ISSUE TITLE
Erroneous URL

### ISSUE THREAD

**Issue by fkru** [blackadderkate/weather-widget-2#26]
Using version 2.1.4 and inserting  lat, lon and alt results in a URL with "lat=...&lon=...&alt=...". However, this URL only works if "alt" is replaced by "altitude".

**Comment by blackadderkate** [comment]
I literally can't believe I didn't notice this!

I've found the bug and have uploaded a fixed version on Github [here](https://github.com/blackadderkate/weather-widget-2/releases/tag/v2.1.6).

**Comment by fkru** [comment]
JFYI: Update to version 2.1.6 via KDE's discover removed all my settings, I am back to Leicester.

**Comment by blackadderkate** [comment]
Oh rats.
The widget name hasn't changed - just the version - so I assumed Discover would treat it as an upgrade...
It's possible I did something wrong when I uploaded the new version on the KDE store. I'm new at this!

I shall have to study the KDE and Pling websites to see what I did wrong...

**Comment by fkru** [comment]
Actullay, Discover offered an update.

**Comment by blackadderkate** [comment]
It seems that Discover (and the "Get New Widgets" feature in KDE) both get their data using the same "API" as the KDE store - which is actually hosted by pling.com. So when I update the widget on Pling / the KDE store, Discover will automatically show it as an update.

What I don't understand is that the name of the widget in the metadata.desktop file hasn't changed, so _in theory_ Discover should have treated it as an update, rather than a brand new install.
I think I'll need to study the documentation on Pling as I obviously did something wrong during the uploading process...

**Comment by fkru** [comment]
Where are the invidual settings stored?
