### ISSUE TITLE
KDE store still has version 2.2.2

### ISSUE THREAD

**Issue by fkru** [blackadderkate/weather-widget-2#99]
Any chance to see an update to the latest version? Thx.

**Comment by martin-ms** [comment]
You can just download the [latest version of the plugin](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.4.2/weather-widget-2.2.4.2.plasmoid) from the developer releases.

The installation works exactly as with the version from the KDE Store and also overrides any installed version of the distributor because it is installed locally in the user environment.

**Comment by fkru** [comment]
> You can just download the [latest version of the plugin](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.4.2/weather-widget-2.2.4.2.plasmoid) from the developer releases.
> 
> The installation works exactly as with the version from the KDE Store and also overrides any installed version of the distributor because it is installed locally in the user environment.
I do know that, but from my experience most of the users are using KDE store and not github dev for downloads.

**Comment by blackadderkate** [comment]
Hi,
After a brief hiatus - due to a new job and major laptop issues - I'm back and devloping again.
I've just uploaded a [new beta version of v2.2.5 ](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.5beta/weather-widget-2.2.5.plasmoid) if you want to try the latest and greatest version...
If I don't find any major bugs, I'll upload it on the KDE store soon...
